using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json.Serialization;
using System.Threading.Tasks;

namespace MongoDB.Model
{
    public class Organization
    {
        public static readonly string DocumentName = "Organizations";
        [JsonIgnore]
        // standard BSonId generated by MongoDb
        public ObjectId _id { get; set; }
        public string Sector { get; set; }
        public string Function { get; set; }
        public string Address { get; set; }
        public string Name { get; set; }
        public bool IsActive { get; set; }
        public string OrganizationId { get; set; }
        public string OrganizationUrl { get; set; }
    }
}
